// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC36yUzx_j2RBOzlzoWzAUQ2aYYhgy61f0',
    appId: '1:942848206044:web:308b057a4dd5b329920019',
    messagingSenderId: '942848206044',
    projectId: 'chat-b1d1a',
    authDomain: 'chat-b1d1a.firebaseapp.com',
    databaseURL: 'https://chat-b1d1a.firebaseio.com',
    storageBucket: 'chat-b1d1a.appspot.com',
    measurementId: 'G-SW3FSE0C2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk00lwasWHkIIdXZ3s0Y8sZphCCo3kNzw',
    appId: '1:942848206044:android:9bb1263f2e8f776a920019',
    messagingSenderId: '942848206044',
    projectId: 'chat-b1d1a',
    databaseURL: 'https://chat-b1d1a.firebaseio.com',
    storageBucket: 'chat-b1d1a.appspot.com',
  );
}
